spring:
  application:
  #服务名称
      name: activiti-demo
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/activiti?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: root
  activiti:
      check-process-definitions: true #自动检查、部署流程定义文件
      database-schema-update: true #自动更新数据库结构
      async-executor-activate: false
      #流程定义文件存放目录
      process-definition-location-prefix: classpath:/processes/
      #process-definition-location-suffixes: #流程文件格式
